### PR TITLE
Fixed detail view of public devices

### PR DESCRIPTION
**Pull request by BiancaWentzel**
The detail view have now a container, breadcrumbs and a footer.
Do we want to have these buttons in the breadcrumbs?

public

### CODE REVIEW

**Comment by octomike** [comment]
Sorry for the late response.
I think showing buttons that don't work should definitely be avoided. It's just too confusing for anyone browsing the public list otherwise.

**Comment by BiancaWentzel** [comment]
I changed the code so that we have no buttons at the top of the detail view.
nobuttons

Or do we want at least have some buttons?

**Comment by octomike** [comment]
Looks good, but the tests failed. Can you remove the reversion change again?

**Comment by BiancaWentzel** [comment]
Changed it.

**Pull request merged**
