### PR TITLE
fix csv write unicode bug

### LINKED ISSUE #197: Csv export from search broken

### PR DESCRIPTION
**Pull request by LizzAlice**

### CODE REVIEW

**Comment by octomike** [comment]
Have you seen this: https://docs.python.org/2/library/csv.html ?

btw, it's enough to mention "fixes #XYZ" in a comment

**Comment by LizzAlice** [comment]
"have you seen this" - posts entire documentation article for csv xD what part of it exactly?

**Comment by octomike** [comment]
It's not that much and most of it is about utf-8 anyway :)

**Comment by LizzAlice** [comment]
but csv.writer is from csv... What I meant to say is that I don't know what you mean by "this" :D

**Comment by LizzAlice** [comment]
fixes #197

**Pull request merged**
